spring.application.name=makemytrip
server.port=8080
spring.data.mongodb.uri=mongodb+srv://root:root@main.upc33tf.mongodb.net/makemytrip?retryWrites=true&w=majority&appName=main
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
 airlabs.api.key=7cedab0b-d3bc-4330-8b0c-8d3bea07be65
                    